import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import EventDesc from "../components/EventDesc";
import EventMap from '../components/EventMap';
import EventImages from '../components/EventImages';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full min-h-screen bg-black text-white">
        <div className="w-full h-[480px] relative">
          <Image src="/img/img1.png" alt="" layout="fill" objectFit="cover" quality={100} />
        </div> 
        <div className="w-full px-[22px] flex items-center justify-center">
          <div className="mt-[20px] mb-[170px] overflow-hidden max-w-[480px] lg:max-w-[784px] xl:max-w-[960px] 2xl:max-w-[1136px] ">
            <EventDesc />
            <EventMap />
            <EventImages />
          </div>
        </div>
      </div>
    </div>
  )
}
